12.05.2025 13:03:27
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
'=' * 20
12.05.2025 13:03:30
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
'=' * 20
12.05.2025 13:03:32
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
'=' * 20
12.05.2025 13:04:33
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
====================
12.05.2025 13:04:34
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
====================
12.05.2025 13:04:35
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
====================
12.05.2025 13:04:35
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
====================
12.05.2025 13:04:36
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123'
====================
12.05.2025 13:06:40
Тип ошибки: Error
Текст ошибки: [('Донор\\Resto.Front.Api.CloudLoyalty.V6.1.0.84', 'Просто бренд/VNBY коломенское \\Resto.Front.Api.CloudLoyalty.V6.1.0.84', "[WinError 3] Системе не удается найти указанный путь: 'Просто бренд/VNBY коломенское \\\\Resto.Front.Api.CloudLoyalty.V6.1.0.84'")]
====================
12.05.2025 13:24:50
Тип ошибки: Error
Текст ошибки: [('Донор\\Resto.Front.Api.CloudLoyalty.V6.1.0.84', 'цшщосцсшо/РРРР \\Resto.Front.Api.CloudLoyalty.V6.1.0.84', "[WinError 3] Системе не удается найти указанный путь: 'цшщосцсшо/РРРР \\\\Resto.Front.Api.CloudLoyalty.V6.1.0.84'")]
====================
12.05.2025 13:45:26
Тип ошибки: FileNotFoundError
Текст ошибки: [Errno 2] No such file or directory: '123/jjjjj /Resto.Front.Api.CloudLoyalty.V6.1.0.84/Resto.Front.Api.CloudLoyalty.dll.config'
====================
12.05.2025 13:46:43
Тип ошибки: FileNotFoundError
Текст ошибки: [Errno 2] No such file or directory: '123/123 /Resto.Front.Api.CloudLoyalty.V6.1.0.84/Resto.Front.Api.CloudLoyalty.dll.config'
====================
12.05.2025 13:50:30
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '1234/'
====================
12.05.2025 14:07:06
Плагины успешно созданы====================
12.05.2025 14:08:38
Плагины успешно созданы
====================
12.05.2025 17:11:25
Плагины успешно созданы
====================
13.05.2025 12:26:28
Тип ошибки: NameError
Текст ошибки: name 'text_edit' is not defined
====================
13.05.2025 12:28:01
Тип ошибки: NameError
Текст ошибки: name 'check_sms' is not defined
====================
13.05.2025 12:33:35
Тип ошибки: NameError
Текст ошибки: name 'check_sms' is not defined
====================
13.05.2025 12:36:20
Плагины успешно созданы
====================
13.05.2025 12:50:58
Плагины успешно созданы
====================
13.05.2025 13:46:33
Плагины успешно созданы
====================
13.05.2025 13:57:12
Плагины успешно созданы
====================
13.05.2025 16:53:44
Плагины успешно созданы
====================
13.05.2025 16:59:56
Плагины успешно созданы
====================
13.05.2025 17:03:09
Плагины успешно созданы
====================
13.05.2025 17:08:39
Плагины успешно созданы
====================
13.05.2025 17:56:42
Плагины успешно созданы
====================
14.05.2025 11:19:47
Плагины успешно созданы
====================
14.05.2025 11:21:37
Плагины успешно созданы
====================
14.05.2025 11:22:22
Плагины успешно созданы
====================
14.05.2025 12:49:12
Плагины успешно созданы
====================
14.05.2025 12:49:25
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: 'Мой бренд'
====================
14.05.2025 12:51:09
Тип ошибки: TypeError
Текст ошибки: append(self, text: Optional[str]): argument 1 has unexpected type 'MyError'
====================
14.05.2025 12:51:12
Тип ошибки: TypeError
Текст ошибки: append(self, text: Optional[str]): argument 1 has unexpected type 'MyError'
====================
14.05.2025 12:51:17
Тип ошибки: TypeError
Текст ошибки: append(self, text: Optional[str]): argument 1 has unexpected type 'MyError'
====================
14.05.2025 13:18:46
Тип ошибки: TypeError
Текст ошибки: append(self, text: Optional[str]): argument 1 has unexpected type 'MyError'
====================
14.05.2025 13:18:49
Тип ошибки: TypeError
Текст ошибки: append(self, text: Optional[str]): argument 1 has unexpected type 'MyError'
====================
14.05.2025 13:18:53
Плагины успешно созданы
====================
14.05.2025 13:19:02
Плагины успешно созданы
====================
14.05.2025 13:28:24
Тип ошибки: TypeError
Текст ошибки: append(self, text: Optional[str]): argument 1 has unexpected type 'MyError'
====================
14.05.2025 13:29:16
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 13:29:32
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 13:30:01
Плагины успешно созданы
====================
14.05.2025 13:30:06
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 13:30:37
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 13:30:38
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 13:30:45
Плагины успешно созданы
====================
14.05.2025 13:31:43
Плагины успешно созданы
====================
14.05.2025 13:31:49
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 13:44:30
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 13:52:26
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '1/'
====================
14.05.2025 13:53:26
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '123/'
====================
14.05.2025 14:09:46
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 14:10:04
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '1/'
====================
14.05.2025 14:10:06
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 14:11:38
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '1/'
====================
14.05.2025 14:12:07
Тип ошибки: TypeError
Текст ошибки: Value after * must be an iterable, not NoneType
====================
14.05.2025 14:12:14
Тип ошибки: FileExistsError
Текст ошибки: [WinError 183] Невозможно создать файл, так как он уже существует: '2/'
====================
14.05.2025 14:12:31
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 14:18:55
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 14:19:05
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 14:19:14
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 14:30:03
Плагины успешно созданы
====================
14.05.2025 14:30:53
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 14:31:00
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 14:35:15
Плагины успешно созданы
====================
14.05.2025 16:41:10
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 16:41:21
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 16:41:33
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 17:20:31
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 17:21:04
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 17:21:07
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 17:21:29
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 17:22:57
Тип ошибки: UnboundLocalError
Текст ошибки: cannot access local variable 'user_api_key' where it is not associated with a value
====================
14.05.2025 17:37:41
Тип ошибки: FileNotFoundError
Текст ошибки: [Errno 2] No such file or directory: '/1/Названия и коды точек.txt'
====================
14.05.2025 17:39:13
Плагины успешно созданы
====================
14.05.2025 17:42:53
Плагины успешно созданы
====================
